package mx.infotec.pacientesms.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AlergiaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlergiaAllPropertiesEquals(Alergia expected, Alergia actual) {
        assertAlergiaAutoGeneratedPropertiesEquals(expected, actual);
        assertAlergiaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlergiaAllUpdatablePropertiesEquals(Alergia expected, Alergia actual) {
        assertAlergiaUpdatableFieldsEquals(expected, actual);
        assertAlergiaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlergiaAutoGeneratedPropertiesEquals(Alergia expected, Alergia actual) {
        assertThat(expected)
            .as("Verify Alergia auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlergiaUpdatableFieldsEquals(Alergia expected, Alergia actual) {
        assertThat(expected)
            .as("Verify Alergia relevant properties")
            .satisfies(e -> assertThat(e.getNombre()).as("check nombre").isEqualTo(actual.getNombre()))
            .satisfies(e -> assertThat(e.getDescripcion()).as("check descripcion").isEqualTo(actual.getDescripcion()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlergiaUpdatableRelationshipsEquals(Alergia expected, Alergia actual) {
        // empty method
    }
}
