package mx.infotec.pacientesms.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CodigoPostalAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCodigoPostalAllPropertiesEquals(CodigoPostal expected, CodigoPostal actual) {
        assertCodigoPostalAutoGeneratedPropertiesEquals(expected, actual);
        assertCodigoPostalAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCodigoPostalAllUpdatablePropertiesEquals(CodigoPostal expected, CodigoPostal actual) {
        assertCodigoPostalUpdatableFieldsEquals(expected, actual);
        assertCodigoPostalUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCodigoPostalAutoGeneratedPropertiesEquals(CodigoPostal expected, CodigoPostal actual) {
        assertThat(expected)
            .as("Verify CodigoPostal auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCodigoPostalUpdatableFieldsEquals(CodigoPostal expected, CodigoPostal actual) {
        assertThat(expected)
            .as("Verify CodigoPostal relevant properties")
            .satisfies(e -> assertThat(e.getCodigo()).as("check codigo").isEqualTo(actual.getCodigo()))
            .satisfies(e -> assertThat(e.getAsentamiento()).as("check asentamiento").isEqualTo(actual.getAsentamiento()))
            .satisfies(e -> assertThat(e.getTipoAsentamiento()).as("check tipoAsentamiento").isEqualTo(actual.getTipoAsentamiento()))
            .satisfies(e -> assertThat(e.getMunicipio()).as("check municipio").isEqualTo(actual.getMunicipio()))
            .satisfies(e -> assertThat(e.getEstado()).as("check estado").isEqualTo(actual.getEstado()))
            .satisfies(e -> assertThat(e.getCiudad()).as("check ciudad").isEqualTo(actual.getCiudad()))
            .satisfies(e ->
                assertThat(e.getCodigoPostalAdministracion())
                    .as("check codigoPostalAdministracion")
                    .isEqualTo(actual.getCodigoPostalAdministracion())
            )
            .satisfies(e -> assertThat(e.getClaveEstado()).as("check claveEstado").isEqualTo(actual.getClaveEstado()))
            .satisfies(e -> assertThat(e.getClaveOficina()).as("check claveOficina").isEqualTo(actual.getClaveOficina()))
            .satisfies(e -> assertThat(e.getClaveCP()).as("check claveCP").isEqualTo(actual.getClaveCP()))
            .satisfies(e ->
                assertThat(e.getClaveTipoAsentamiento()).as("check claveTipoAsentamiento").isEqualTo(actual.getClaveTipoAsentamiento())
            )
            .satisfies(e -> assertThat(e.getClaveMunicipio()).as("check claveMunicipio").isEqualTo(actual.getClaveMunicipio()))
            .satisfies(e -> assertThat(e.getIdAsentamientoCons()).as("check idAsentamientoCons").isEqualTo(actual.getIdAsentamientoCons()))
            .satisfies(e -> assertThat(e.getZona()).as("check zona").isEqualTo(actual.getZona()))
            .satisfies(e -> assertThat(e.getClaveCiudad()).as("check claveCiudad").isEqualTo(actual.getClaveCiudad()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCodigoPostalUpdatableRelationshipsEquals(CodigoPostal expected, CodigoPostal actual) {
        // empty method
    }
}
