package mx.infotec.pacientesms.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DireccionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDireccionAllPropertiesEquals(Direccion expected, Direccion actual) {
        assertDireccionAutoGeneratedPropertiesEquals(expected, actual);
        assertDireccionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDireccionAllUpdatablePropertiesEquals(Direccion expected, Direccion actual) {
        assertDireccionUpdatableFieldsEquals(expected, actual);
        assertDireccionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDireccionAutoGeneratedPropertiesEquals(Direccion expected, Direccion actual) {
        assertThat(expected)
            .as("Verify Direccion auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDireccionUpdatableFieldsEquals(Direccion expected, Direccion actual) {
        assertThat(expected)
            .as("Verify Direccion relevant properties")
            .satisfies(e -> assertThat(e.getNombreVialidad()).as("check nombreVialidad").isEqualTo(actual.getNombreVialidad()))
            .satisfies(e -> assertThat(e.getNumExterior()).as("check numExterior").isEqualTo(actual.getNumExterior()))
            .satisfies(e -> assertThat(e.getNumInterior()).as("check numInterior").isEqualTo(actual.getNumInterior()))
            .satisfies(e -> assertThat(e.getTelefono()).as("check telefono").isEqualTo(actual.getTelefono()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDireccionUpdatableRelationshipsEquals(Direccion expected, Direccion actual) {
        assertThat(expected)
            .as("Verify Direccion relationships")
            .satisfies(e -> assertThat(e.getTipoVialidad()).as("check tipoVialidad").isEqualTo(actual.getTipoVialidad()))
            .satisfies(e -> assertThat(e.getCodigoPostalInfo()).as("check codigoPostalInfo").isEqualTo(actual.getCodigoPostalInfo()))
            .satisfies(e -> assertThat(e.getEntidadFederativa()).as("check entidadFederativa").isEqualTo(actual.getEntidadFederativa()));
    }
}
