package mx.infotec.pacientesms.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EntidadFederativaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntidadFederativaAllPropertiesEquals(EntidadFederativa expected, EntidadFederativa actual) {
        assertEntidadFederativaAutoGeneratedPropertiesEquals(expected, actual);
        assertEntidadFederativaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntidadFederativaAllUpdatablePropertiesEquals(EntidadFederativa expected, EntidadFederativa actual) {
        assertEntidadFederativaUpdatableFieldsEquals(expected, actual);
        assertEntidadFederativaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntidadFederativaAutoGeneratedPropertiesEquals(EntidadFederativa expected, EntidadFederativa actual) {
        assertThat(expected)
            .as("Verify EntidadFederativa auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntidadFederativaUpdatableFieldsEquals(EntidadFederativa expected, EntidadFederativa actual) {
        assertThat(expected)
            .as("Verify EntidadFederativa relevant properties")
            .satisfies(e -> assertThat(e.getClave()).as("check clave").isEqualTo(actual.getClave()))
            .satisfies(e -> assertThat(e.getNombre()).as("check nombre").isEqualTo(actual.getNombre()))
            .satisfies(e -> assertThat(e.getAbreviatura()).as("check abreviatura").isEqualTo(actual.getAbreviatura()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntidadFederativaUpdatableRelationshipsEquals(EntidadFederativa expected, EntidadFederativa actual) {
        // empty method
    }
}
