package mx.infotec.pacientesms.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class HistorialMedicoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistorialMedicoAllPropertiesEquals(HistorialMedico expected, HistorialMedico actual) {
        assertHistorialMedicoAutoGeneratedPropertiesEquals(expected, actual);
        assertHistorialMedicoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistorialMedicoAllUpdatablePropertiesEquals(HistorialMedico expected, HistorialMedico actual) {
        assertHistorialMedicoUpdatableFieldsEquals(expected, actual);
        assertHistorialMedicoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistorialMedicoAutoGeneratedPropertiesEquals(HistorialMedico expected, HistorialMedico actual) {
        assertThat(expected)
            .as("Verify HistorialMedico auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistorialMedicoUpdatableFieldsEquals(HistorialMedico expected, HistorialMedico actual) {
        assertThat(expected)
            .as("Verify HistorialMedico relevant properties");
    }


    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistorialMedicoUpdatableRelationshipsEquals(HistorialMedico expected, HistorialMedico actual) {
        // empty method
    }
}
