package mx.infotec.pacientesms.domain;

import static mx.infotec.pacientesms.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class InfoSocioeconomicaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInfoSocioeconomicaAllPropertiesEquals(InfoSocioeconomica expected, InfoSocioeconomica actual) {
        assertInfoSocioeconomicaAutoGeneratedPropertiesEquals(expected, actual);
        assertInfoSocioeconomicaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInfoSocioeconomicaAllUpdatablePropertiesEquals(InfoSocioeconomica expected, InfoSocioeconomica actual) {
        assertInfoSocioeconomicaUpdatableFieldsEquals(expected, actual);
        assertInfoSocioeconomicaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInfoSocioeconomicaAutoGeneratedPropertiesEquals(InfoSocioeconomica expected, InfoSocioeconomica actual) {
        assertThat(expected)
            .as("Verify InfoSocioeconomica auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInfoSocioeconomicaUpdatableFieldsEquals(InfoSocioeconomica expected, InfoSocioeconomica actual) {
        assertThat(expected)
            .as("Verify InfoSocioeconomica relevant properties")
            .satisfies(e -> assertThat(e.getTipoVivienda()).as("check tipoVivienda").isEqualTo(actual.getTipoVivienda()))
            .satisfies(e -> assertThat(e.getMaterialVivienda()).as("check materialVivienda").isEqualTo(actual.getMaterialVivienda()))
            .satisfies(e -> assertThat(e.getNumeroHabitaciones()).as("check numeroHabitaciones").isEqualTo(actual.getNumeroHabitaciones()))
            .satisfies(e -> assertThat(e.getNumeroHabitantes()).as("check numeroHabitantes").isEqualTo(actual.getNumeroHabitantes()))
            .satisfies(e ->
                assertThat(e.getServiciosDisponibles()).as("check serviciosDisponibles").isEqualTo(actual.getServiciosDisponibles())
            )
            .satisfies(e ->
                assertThat(e.getIngresoMensual())
                    .as("check ingresoMensual")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(actual.getIngresoMensual())
            )
            .satisfies(e ->
                assertThat(e.getIngresoMensualHogar())
                    .as("check ingresoMensualHogar")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(actual.getIngresoMensualHogar())
            )
            .satisfies(e ->
                assertThat(e.getGastoMensual())
                    .as("check gastoMensual")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(actual.getGastoMensual())
            )
            .satisfies(e ->
                assertThat(e.getPersonasDependientes()).as("check personasDependientes").isEqualTo(actual.getPersonasDependientes())
            )
            .satisfies(e ->
                assertThat(e.getApoyosGubernamentales()).as("check apoyosGubernamentales").isEqualTo(actual.getApoyosGubernamentales())
            )
            .satisfies(e -> assertThat(e.getOcupacionActual()).as("check ocupacionActual").isEqualTo(actual.getOcupacionActual()))
            .satisfies(e -> assertThat(e.getCondicionLaboral()).as("check condicionLaboral").isEqualTo(actual.getCondicionLaboral()))
            .satisfies(e -> assertThat(e.getTipoEmpleo()).as("check tipoEmpleo").isEqualTo(actual.getTipoEmpleo()))
            .satisfies(e -> assertThat(e.getLugarTrabajo()).as("check lugarTrabajo").isEqualTo(actual.getLugarTrabajo()))
            .satisfies(e -> assertThat(e.getTiempoEmpleado()).as("check tiempoEmpleado").isEqualTo(actual.getTiempoEmpleado()))
            .satisfies(e ->
                assertThat(e.getGradoMaximoEstudios()).as("check gradoMaximoEstudios").isEqualTo(actual.getGradoMaximoEstudios())
            )
            .satisfies(e -> assertThat(e.getAniosEstudio()).as("check aniosEstudio").isEqualTo(actual.getAniosEstudio()))
            .satisfies(e -> assertThat(e.getEstudia()).as("check estudia").isEqualTo(actual.getEstudia()))
            .satisfies(e -> assertThat(e.getInstitucionMedica()).as("check institucionMedica").isEqualTo(actual.getInstitucionMedica()))
            .satisfies(e -> assertThat(e.getTipoAfiliacion()).as("check tipoAfiliacion").isEqualTo(actual.getTipoAfiliacion()))
            .satisfies(e -> assertThat(e.getNumeroAfiliacion()).as("check numeroAfiliacion").isEqualTo(actual.getNumeroAfiliacion()))
            .satisfies(e -> assertThat(e.getMedioTransporte()).as("check medioTransporte").isEqualTo(actual.getMedioTransporte()))
            .satisfies(e -> assertThat(e.getTiempoTraslado()).as("check tiempoTraslado").isEqualTo(actual.getTiempoTraslado()))
            .satisfies(e -> assertThat(e.getFechaActualizacion()).as("check fechaActualizacion").isEqualTo(actual.getFechaActualizacion()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInfoSocioeconomicaUpdatableRelationshipsEquals(InfoSocioeconomica expected, InfoSocioeconomica actual) {
        // empty method
    }
}
