package mx.infotec.pacientesms.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PacienteAlergiaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPacienteAlergiaAllPropertiesEquals(PacienteAlergia expected, PacienteAlergia actual) {
        assertPacienteAlergiaAutoGeneratedPropertiesEquals(expected, actual);
        assertPacienteAlergiaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPacienteAlergiaAllUpdatablePropertiesEquals(PacienteAlergia expected, PacienteAlergia actual) {
        assertPacienteAlergiaUpdatableFieldsEquals(expected, actual);
        assertPacienteAlergiaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPacienteAlergiaAutoGeneratedPropertiesEquals(PacienteAlergia expected, PacienteAlergia actual) {
        assertThat(expected)
            .as("Verify PacienteAlergia auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPacienteAlergiaUpdatableFieldsEquals(PacienteAlergia expected, PacienteAlergia actual) {
        assertThat(expected)
            .as("Verify PacienteAlergia relevant properties")
            .satisfies(e -> assertThat(e.getFechaDeteccion()).as("check fechaDeteccion").isEqualTo(actual.getFechaDeteccion()))
            .satisfies(e -> assertThat(e.getReaccion()).as("check reaccion").isEqualTo(actual.getReaccion()))
            .satisfies(e -> assertThat(e.getGravedad()).as("check gravedad").isEqualTo(actual.getGravedad()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPacienteAlergiaUpdatableRelationshipsEquals(PacienteAlergia expected, PacienteAlergia actual) {
        assertThat(expected)
            .as("Verify PacienteAlergia relationships")
            .satisfies(e -> assertThat(e.getPaciente()).as("check paciente").isEqualTo(actual.getPaciente()))
            .satisfies(e -> assertThat(e.getAlergia()).as("check alergia").isEqualTo(actual.getAlergia()));
    }
}
