package mx.infotec.pacientesms.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PacienteAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPacienteAllPropertiesEquals(Paciente expected, Paciente actual) {
        assertPacienteAutoGeneratedPropertiesEquals(expected, actual);
        assertPacienteAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPacienteAllUpdatablePropertiesEquals(Paciente expected, Paciente actual) {
        assertPacienteUpdatableFieldsEquals(expected, actual);
        assertPacienteUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPacienteAutoGeneratedPropertiesEquals(Paciente expected, Paciente actual) {
        assertThat(expected)
            .as("Verify Paciente auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPacienteUpdatableFieldsEquals(Paciente expected, Paciente actual) {
        assertThat(expected)
            .as("Verify Paciente relevant properties")
            .satisfies(e -> assertThat(e.getEcu()).as("check ecu").isEqualTo(actual.getEcu()))
            .satisfies(e -> assertThat(e.getNombre()).as("check nombre").isEqualTo(actual.getNombre()))
            .satisfies(e -> assertThat(e.getApellidoPaterno()).as("check apellidoPaterno").isEqualTo(actual.getApellidoPaterno()))
            .satisfies(e -> assertThat(e.getApellidoMaterno()).as("check apellidoMaterno").isEqualTo(actual.getApellidoMaterno()))
            .satisfies(e -> assertThat(e.getSexo()).as("check sexo").isEqualTo(actual.getSexo()))
            .satisfies(e -> assertThat(e.getNacionalidad()).as("check nacionalidad").isEqualTo(actual.getNacionalidad()))
            .satisfies(e -> assertThat(e.getFechaNacimiento()).as("check fechaNacimiento").isEqualTo(actual.getFechaNacimiento()))
            .satisfies(e -> assertThat(e.getEstadoCivil()).as("check estadoCivil").isEqualTo(actual.getEstadoCivil()))
            .satisfies(e -> assertThat(e.getCurp()).as("check curp").isEqualTo(actual.getCurp()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPacienteUpdatableRelationshipsEquals(Paciente expected, Paciente actual) {
        assertThat(expected)
            .as("Verify Paciente relationships")
            .satisfies(e -> assertThat(e.getDireccion()).as("check direccion").isEqualTo(actual.getDireccion()))
            .satisfies(e -> assertThat(e.getInfoSocioeconomica()).as("check infoSocioeconomica").isEqualTo(actual.getInfoSocioeconomica()))
            .satisfies(e -> assertThat(e.getHistorialGeneral()).as("check historialGeneral").isEqualTo(actual.getHistorialGeneral()))
            .satisfies(e -> assertThat(e.getEntidadNacimiento()).as("check entidadNacimiento").isEqualTo(actual.getEntidadNacimiento()));
    }
}
