package mx.infotec.pacientesms.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PacienteEnfermedadAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPacienteEnfermedadAllPropertiesEquals(PacienteEnfermedad expected, PacienteEnfermedad actual) {
        assertPacienteEnfermedadAutoGeneratedPropertiesEquals(expected, actual);
        assertPacienteEnfermedadAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPacienteEnfermedadAllUpdatablePropertiesEquals(PacienteEnfermedad expected, PacienteEnfermedad actual) {
        assertPacienteEnfermedadUpdatableFieldsEquals(expected, actual);
        assertPacienteEnfermedadUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPacienteEnfermedadAutoGeneratedPropertiesEquals(PacienteEnfermedad expected, PacienteEnfermedad actual) {
        assertThat(expected)
            .as("Verify PacienteEnfermedad auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPacienteEnfermedadUpdatableFieldsEquals(PacienteEnfermedad expected, PacienteEnfermedad actual) {
        assertThat(expected)
            .as("Verify PacienteEnfermedad relevant properties")
            .satisfies(e -> assertThat(e.getFechaDiagnostico()).as("check fechaDiagnostico").isEqualTo(actual.getFechaDiagnostico()))
            .satisfies(e -> assertThat(e.getEstado()).as("check estado").isEqualTo(actual.getEstado()))
            .satisfies(e -> assertThat(e.getNotas()).as("check notas").isEqualTo(actual.getNotas()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPacienteEnfermedadUpdatableRelationshipsEquals(PacienteEnfermedad expected, PacienteEnfermedad actual) {
        assertThat(expected)
            .as("Verify PacienteEnfermedad relationships")
            .satisfies(e -> assertThat(e.getPaciente()).as("check paciente").isEqualTo(actual.getPaciente()))
            .satisfies(e -> assertThat(e.getEnfermedad()).as("check enfermedad").isEqualTo(actual.getEnfermedad()));
    }
}
