package mx.infotec.pacientesms.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PacienteMedicamentoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPacienteMedicamentoAllPropertiesEquals(PacienteMedicamento expected, PacienteMedicamento actual) {
        assertPacienteMedicamentoAutoGeneratedPropertiesEquals(expected, actual);
        assertPacienteMedicamentoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPacienteMedicamentoAllUpdatablePropertiesEquals(PacienteMedicamento expected, PacienteMedicamento actual) {
        assertPacienteMedicamentoUpdatableFieldsEquals(expected, actual);
        assertPacienteMedicamentoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPacienteMedicamentoAutoGeneratedPropertiesEquals(PacienteMedicamento expected, PacienteMedicamento actual) {
        assertThat(expected)
            .as("Verify PacienteMedicamento auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPacienteMedicamentoUpdatableFieldsEquals(PacienteMedicamento expected, PacienteMedicamento actual) {
        assertThat(expected)
            .as("Verify PacienteMedicamento relevant properties")
            .satisfies(e -> assertThat(e.getDosis()).as("check dosis").isEqualTo(actual.getDosis()))
            .satisfies(e -> assertThat(e.getFrecuencia()).as("check frecuencia").isEqualTo(actual.getFrecuencia()))
            .satisfies(e -> assertThat(e.getFechaInicio()).as("check fechaInicio").isEqualTo(actual.getFechaInicio()))
            .satisfies(e -> assertThat(e.getFechaFin()).as("check fechaFin").isEqualTo(actual.getFechaFin()))
            .satisfies(e -> assertThat(e.getActivo()).as("check activo").isEqualTo(actual.getActivo()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPacienteMedicamentoUpdatableRelationshipsEquals(PacienteMedicamento expected, PacienteMedicamento actual) {
        assertThat(expected)
            .as("Verify PacienteMedicamento relationships")
            .satisfies(e -> assertThat(e.getPaciente()).as("check paciente").isEqualTo(actual.getPaciente()))
            .satisfies(e -> assertThat(e.getMedicamento()).as("check medicamento").isEqualTo(actual.getMedicamento()));
    }
}
