package mx.infotec.pacientesms.domain;

import static mx.infotec.pacientesms.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class SignosVitalesAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSignosVitalesAllPropertiesEquals(SignosVitales expected, SignosVitales actual) {
        assertSignosVitalesAutoGeneratedPropertiesEquals(expected, actual);
        assertSignosVitalesAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSignosVitalesAllUpdatablePropertiesEquals(SignosVitales expected, SignosVitales actual) {
        assertSignosVitalesUpdatableFieldsEquals(expected, actual);
        assertSignosVitalesUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSignosVitalesAutoGeneratedPropertiesEquals(SignosVitales expected, SignosVitales actual) {
        assertThat(expected)
            .as("Verify SignosVitales auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSignosVitalesUpdatableFieldsEquals(SignosVitales expected, SignosVitales actual) {
        assertThat(expected)
            .as("Verify SignosVitales relevant properties")
            .satisfies(e -> assertThat(e.getFechaRegistro()).as("check fechaRegistro").isEqualTo(actual.getFechaRegistro()))
            .satisfies(e -> assertThat(e.getFrecuenciaCardiaca()).as("check frecuenciaCardiaca").isEqualTo(actual.getFrecuenciaCardiaca()))
            .satisfies(e -> assertThat(e.getTensionArterial()).as("check tensionArterial").isEqualTo(actual.getTensionArterial()))
            .satisfies(e ->
                assertThat(e.getFrecuenciaRespiratoria()).as("check frecuenciaRespiratoria").isEqualTo(actual.getFrecuenciaRespiratoria())
            )
            .satisfies(e ->
                assertThat(e.getTemperatura())
                    .as("check temperatura")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(actual.getTemperatura())
            )
            .satisfies(e -> assertThat(e.getSaturacionOxigeno()).as("check saturacionOxigeno").isEqualTo(actual.getSaturacionOxigeno()))
            .satisfies(e -> assertThat(e.getPeso()).as("check peso").usingComparator(bigDecimalCompareTo).isEqualTo(actual.getPeso()))
            .satisfies(e ->
                assertThat(e.getEstatura()).as("check estatura").usingComparator(bigDecimalCompareTo).isEqualTo(actual.getEstatura())
            )
            .satisfies(e -> assertThat(e.getImc()).as("check imc").usingComparator(bigDecimalCompareTo).isEqualTo(actual.getImc()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSignosVitalesUpdatableRelationshipsEquals(SignosVitales expected, SignosVitales actual) {
        assertThat(expected)
            .as("Verify SignosVitales relationships")
            .satisfies(e -> assertThat(e.getPaciente()).as("check paciente").isEqualTo(actual.getPaciente()));
    }
}
