package mx.infotec.pacientesms.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TipoVialidadAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoVialidadAllPropertiesEquals(TipoVialidad expected, TipoVialidad actual) {
        assertTipoVialidadAutoGeneratedPropertiesEquals(expected, actual);
        assertTipoVialidadAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoVialidadAllUpdatablePropertiesEquals(TipoVialidad expected, TipoVialidad actual) {
        assertTipoVialidadUpdatableFieldsEquals(expected, actual);
        assertTipoVialidadUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoVialidadAutoGeneratedPropertiesEquals(TipoVialidad expected, TipoVialidad actual) {
        assertThat(expected)
            .as("Verify TipoVialidad auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoVialidadUpdatableFieldsEquals(TipoVialidad expected, TipoVialidad actual) {
        assertThat(expected)
            .as("Verify TipoVialidad relevant properties")
            .satisfies(e -> assertThat(e.getNombre()).as("check nombre").isEqualTo(actual.getNombre()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoVialidadUpdatableRelationshipsEquals(TipoVialidad expected, TipoVialidad actual) {
        // empty method
    }
}
